server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.cn
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka/
