server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB2022?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.binbin.springcloud.entities
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  #表示从服务端抓取已有的注册信息，集群需要设置为true方便配合负载均衡
    service-url:  #设置注册地址
      defaultZone: http://eureka7001.cn:7001/eureka,http://eureka7002.cn:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问时现实ip地址
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务端发送心跳的间隔时间，默认是30s
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到客户端最后一次心跳的等待时间上限（默认90），超时则剔除